/** pokemon-cards-css stylesheets — card holo only (no global.css — it breaks app layout) */

export const POKEMON_CARD_STYLES = [
  "/pokemon-cards-css/css/cards/base.css",
  "/pokemon-cards-css/css/cards.css",
  "/pokemon-cards-css/css/cards/basic.css",
  "/pokemon-cards-css/css/cards/reverse-holo.css",
  "/pokemon-cards-css/css/cards/regular-holo.css",
  "/pokemon-cards-css/css/cards/cosmos-holo.css",
  "/pokemon-cards-css/css/cards/amazing-rare.css",
  "/pokemon-cards-css/css/cards/radiant-holo.css",
  "/pokemon-cards-css/css/cards/v-regular.css",
  "/pokemon-cards-css/css/cards/v-full-art.css",
  "/pokemon-cards-css/css/cards/v-max.css",
  "/pokemon-cards-css/css/cards/v-star.css",
  "/pokemon-cards-css/css/cards/trainer-full-art.css",
  "/pokemon-cards-css/css/cards/rainbow-holo.css",
  "/pokemon-cards-css/css/cards/rainbow-alt.css",
  "/pokemon-cards-css/css/cards/secret-rare.css",
  "/pokemon-cards-css/css/cards/trainer-gallery-holo.css",
  "/pokemon-cards-css/css/cards/trainer-gallery-v-regular.css",
  "/pokemon-cards-css/css/cards/trainer-gallery-v-max.css",
  "/pokemon-cards-css/css/cards/trainer-gallery-secret-rare.css",
  "/pokemon-cards-css/css/cards/shiny-rare.css",
  "/pokemon-cards-css/css/cards/shiny-v.css",
  "/pokemon-cards-css/css/cards/shiny-vmax.css",
  "/pokemon-cards-css/css/cards/swsh-pikachu.css",
  "/pokemon-cards-css/css/huggimon.css",
] as const;
